# Generated by Django 5.2 on 2025-05-07 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='Country',
            new_name='country',
        ),
    ]
