import type { Metadata } from "next";
import Navbar from "./components/navbar/navbar";
import "./globals.css";

export const metadata: Metadata = {
  title: "DjangoBNB",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="pb-[150px]">
          <Navbar/>
        </div>
        {children}
      </body>
    </html>
  );
}
