import type { Metadata } from "next";
import Navbar from "./components/navbar/navbar";
import LoginModal from "./components/modals/LoginModal";
import SignupModal from "./components/modals/SignupModal";
import AddPropertyModal from "./components/modals/AddPropertyModal";
import "./globals.css";

export const metadata: Metadata = {
  title: "DjangoBNB",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const content=(
    <p>yo</p>
  )

  return (
    <html lang="en">
      <body>
        <div className="pb-[150px]">
          <Navbar/>
        </div>
        <div>
        {children}
        </div>

        <LoginModal/>
        <SignupModal/>
        <AddPropertyModal/>
      </body>
    </html>
  );
}
