name: Deploy Django App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/djangobnb_backend/requirements.txt

    - name: Run migrations and collect static
      env:
        SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        DJANGO_ALLOWED_HOSTS: ${{ secrets.DJANGO_ALLOWED_HOSTS }}
        DEBUG: ${{ secrets.DEBUG }}
        SQL_ENGINE: ${{ secrets.SQL_ENGINE }}
        SQL_DATABASE: ${{ secrets.SQL_DATABASE }}
        SQL_USER: ${{ secrets.SQL_USER }}
        SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
        SQL_HOST: ${{ secrets.SQL_HOST }}
        SQL_PORT: ${{ secrets.SQL_PORT }}
      run: |
        python backend/djangobnb_backend/manage.py check --deploy
        python backend/djangobnb_backend/manage.py migrate
        python backend/djangobnb_backend/manage.py collectstatic --noinput

    - name: Deploy to Server via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        script: |
          cd /path/to/project
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          python backend/djangobnb_backend/manage.py migrate
          python backend/djangobnb_backend/manage.py collectstatic --noinput
          sudo systemctl restart gunicorn
          sudo systemctl restart nginx